### ISSUE TITLE
Design branch merge

### ISSUE THREAD

**Issue by benrito** [theirc/airbel#10]
Hi @tbeck and Jenny — can you provide an ETA for merging of design branch?

We are on standby to help bring across the line. Making time today and end week to assist with getting everything complete on staging.

Thanks!

**Comment by tbeck** [comment]
Hi @benrito - We will be merging the design branch today. It might be helpful to schedule a quick review for tomorrow to flesh out remaining steps/tasks to launch. 

I can send over some available times in our schedule if that sounds good?

Thanks!
T

**Comment by benrito** [comment]
wonderful and glad to hear! 

please do send over any times that work for you all—we can move some stuff around if necessary.

at the moment, 12pm EST and 4pm EST tomorrow would work.

cheers,
ben

**Comment by tbeck** [comment]
Thanks @benrito - Just sent an invitation for 4pm EST.
