### ISSUE TITLE
data model - portfolio stages

### ISSUE THREAD

**Issue by abandea** [theirc/airbel#11]
Hi @tbeck,

Currently the stages are as such:
1. Identify 2. Design/Research 3. Design/Solution Generation 4. Design/Prototype 5. Test/Pilot 6. Test/Rigorous Evaluation 7. Scale 

Could we remove "Identify" as that's synonymous with " Design/Research" and instead have 6 stages. So it would then be 1. Design/Research, 2. Design/Solution, etc to 6. Scale 

Apologies for the potential confusion, but @benrito and I think 6 stages will do!

Thanks!

**Comment by tbeck** [comment]
These have been updated and logic added to templates.
