### ISSUE TITLE
portfolio drop down - filter by location

### ISSUE THREAD

**Issue by abandea** [theirc/airbel#12]
in addition to focus

**Comment by tbeck** [comment]
@abandea & @benrito 
I am a bit confused by the similarities between these two sections of the portfolio page.

Project List:
[![Screenshot from Gyazo](https://gyazo.com/33f0d78ce02561301d631560225bdaf5/raw)](https://gyazo.com/33f0d78ce02561301d631560225bdaf5)

Portfolio Visualizer (list view)
[![Screenshot from Gyazo](https://gyazo.com/8c89ae454e2c91d0d08cb4b516169891/raw)](https://gyazo.com/8c89ae454e2c91d0d08cb4b516169891)

There seems like this has evolved into very similar content and now we have multiple filters effecting different sections. 

Is it worth considering combining these sections?

Thanks!

**Comment by tbeck** [comment]
hi @abandea - Can you review and close if this issue is resolved with the recent changes?

Thanks!

**Comment by benrito** [comment]
This is looking great. Closing. Thanks!
