### ISSUE TITLE
Show graduated filter in portfolio 

### ISSUE THREAD

**Issue by abandea** [theirc/airbel#14]

**Comment by tbeck** [comment]
added multifilter and additional UI element for filter by status.

commit: 9ad95e9

**Comment by tbeck** [comment]
@abandea - We now have multiple filters on this page and there are several instances that result in no results. I feel like this may warrant further conversation to clearly understand what the use cases are and if each filter is necessary?

**Comment by abandea** [comment]
See https://github.com/ocupop/airbel/issues/25#issue-366057901

**Comment by tbeck** [comment]
Reassigning for review.

**Comment by benrito** [comment]
This is working great. Thanks!
