### ISSUE TITLE
Hide advisors section

### ISSUE THREAD

**Issue by abandea** [theirc/airbel#18]
Hey we were hoping to have a list of advisors by now, but we currently don't them. Can we hide that section? Looks like I can't delete the last one (Natan)

**Comment by tbeck** [comment]
Hi @abandea - We added template logic to hide the section if no advisors exist and removed Natan.

commit: c9cc77f 

Let me know if you would like me to close these issues as we push fixes? Or allow you to review and close them?

Thanks!

**Comment by abandea** [comment]
Thanks, looking good! I can close them out!
