### ISSUE TITLE
character count for Description field

### ISSUE THREAD

**Issue by abandea** [theirc/airbel#19]
Hi @tbeck!

Would you happen to know what the ideal character count is for the description field in relation to the portfolio? Just want to make sure the most important info doesn't get cut off. 

Thanks!

**Comment by tbeck** [comment]
We currently are not limiting the character count on the descriptions in the portfolio page, but I feel like the safe range to avoid large amounts of negative space is between 200 - 350.

The Coach Everu project is currently at 533 and creates some negative space on smaller screens, but not to bad.

**Comment by abandea** [comment]
Thanks that's helpful! I was talking about character count before it get cuts off by ellipsis. Looks like, currently, around 186 characters is the most it can hold before it cuts off. 

<img width="1079" alt="screen shot 2018-10-01 at 17 43 23" src="https://user-images.githubusercontent.com/42815657/46317634-a8f78380-c5a1-11e8-991f-83b14453eb91.png">
