### ISSUE TITLE
Make repo public?

### ISSUE THREAD

**Issue by benrito** [theirc/airbel#2]
What do you think @tbeck ?

**Comment by tbeck** [comment]
It's currently set to public to avoid Github's price per seat charges, but I have don't have an overwhelming opinion either way. 
We have been using Bitbucket more these days because of their pricing model for private repos.

**Comment by benrito** [comment]
Ah! My bad, I thought it was private. I was trying to set up an integration with Slack but it didn’t work. I think I need higher privileges.

**Comment by tbeck** [comment]
Ahhh... gotcha. I have everyone set up with admin privileges on this end, but let me know if there are any other changes we can make.
