### ISSUE TITLE
project pages - image specs for header image 

### ISSUE THREAD

**Issue by abandea** [theirc/airbel#20]
@tbeck similarly to character count, what is the ideal size or ratio for header images on project pages?

**Comment by tbeck** [comment]
Hi @abandea - Currently the aspect ratio for those images is 14x5. Or 1400x500px.

However, this may need to be adjusted based on "real world images" so let me know if you are having difficulty finding good images that crop well at that aspect ratio and we can adjust the template.

**Comment by abandea** [comment]
Hey @tbeck! 

The images work well on the All Projects section: 
<img width="793" alt="screen shot 2018-10-02 at 17 05 21" src="https://user-images.githubusercontent.com/42815657/46376992-7747f080-c665-11e8-8bf3-b2ed2131fa05.png">

But I am having a tough time finding images that crop well on the project page: 
<img width="1340" alt="screen shot 2018-10-02 at 17 05 38" src="https://user-images.githubusercontent.com/42815657/46377011-82028580-c665-11e8-92d5-bcbcc0de21e2.png">

Is there a way to add a separate image field, so I can adjust the crop for the project page if I need to? Or open to other convenient solutions!

**Comment by tbeck** [comment]
Hi @abandea - Sure thing... We have pushed adjustments to the data model and added another field for the "hero" image so that you can utilize different images if necessary.

commit: c48d2f5

Let me know if this needs any further adjustments?

Thanks!
