### ISSUE TITLE
project page - Forgo View button under Resources

### ISSUE THREAD

**Issue by abandea** [theirc/airbel#21]
Nitpicky and low-priority: any way we can forgo the "View button" and just link the bulleted item to simplify?

<img width="412" alt="screen shot 2018-09-28 at 17 05 25" src="https://user-images.githubusercontent.com/42815657/46233517-ead5bf00-c340-11e8-8383-48e64c48bed4.png">

**Comment by jonathanwburr** [comment]
Commit: dd78adc

**Comment by abandea** [comment]
Hiya @jonathanwburr! Can we hyperlink the bulleted item, such as items under "Related Articles" 

<img width="1112" alt="screen shot 2018-10-01 at 17 35 16" src="https://user-images.githubusercontent.com/42815657/46317237-67b2a400-c5a0-11e8-8d11-27d158dbfba7.png">

**Comment by abandea** [comment]
Nevermind, works for new items!
