### ISSUE TITLE
Portfolio visualizer - add tooltips to gridview

### ISSUE THREAD

**Issue by abandea** [theirc/airbel#24]

**Comment by jennyvanderheiden** [comment]
@abandea Tooltip is a good idea and we think it should reflect the same look as the indicator with the dark box and arrow: https://gyazo.com/b65ed96e2ca6454080922541d818d067

Also want to touch base on the grid view in the different statuses:
active: https://gyazo.com/b65ed96e2ca6454080922541d818d067
graduated: https://gyazo.com/b3803c602fdcb67e3af317f3934ef654
discontinued: https://gyazo.com/91148aa8905dfcf8b91da949c76605a5

**Comment by benrito** [comment]
I think it could work either way. It looks neat and compact now but the data model gives us a built in set of content for this.

**Comment by benrito** [comment]
Agree @tbeck — think title only looks more elegant.
