### ISSUE TITLE
filter should be for All Projects; not Portfolio

### ISSUE THREAD

**Issue by abandea** [theirc/airbel#25]
Re: your previous comments regarding the difference between the Portfolio and the All Projects sections + filters

Could we move all filter configurations (location + focuses) to the All Projects section, and leave the Portfolio visualizer with no filter (with the exception of Graduated...which I'll elaborate on in another issue).

**Comment by tbeck** [comment]
Hi @abandea!
Changes are in place now on staging. I am reassigning to you to review.

https://icy-ship.cloudvent.net/portfolio

Thanks!
