### ISSUE TITLE
All projects: Add button to clear all filters

### ISSUE THREAD

**Issue by abandea** [theirc/airbel#26]

**Comment by jennyvanderheiden** [comment]
@abandea 

We are proposing the implementation a clear button in a field in the same place as the text indicating what the user is currently looking at: https://gyazo.com/eb905dcb27547b86896e87cd37be084d

**Comment by abandea** [comment]
@jennyvanderheiden I think that works!

**Comment by tbeck** [comment]
@abandea - There is now a clear filter solution. Adding @jonathanwburr for any follow up adjustments.

**Comment by abandea** [comment]
Thanks @tbeck! @jonathanwburr I see the clear filter solution, but doesn't seem to function yet

**Comment by tbeck** [comment]
Hi @abandea - I apologize, I just pushed a fix for the functionality.
