### ISSUE TITLE
Portfolio visualizer: Do not show graduated projects by default

### ISSUE THREAD

**Issue by abandea** [theirc/airbel#27]
Removing the remaining filters, can we add a graduated button or filter that will populate the portfolio?

**Comment by jennyvanderheiden** [comment]
@abandea see solution to issue #30

**Comment by tbeck** [comment]
@abandea - Can you review the current staging and let me know if the solutions in place solve this issue?

https://icy-ship.cloudvent.net/portfolio

Thanks!
T
