### ISSUE TITLE
Portfolio view - simplify text (stage + focus) 

### ISSUE THREAD

**Issue by abandea** [theirc/airbel#28]
The stages and the focus are currently drowning out the Solution name and the location. Could we remove the Stage (and they're already shown in the pipeline) and somehow put less emphasis on the Focus?

<img width="1083" alt="screen shot 2018-10-02 at 16 36 50" src="https://user-images.githubusercontent.com/42815657/46375500-98a6dd80-c661-11e8-89d6-f6751ec070da.png">

**Comment by jennyvanderheiden** [comment]
@abandea We are adjusting to reduce the size of the focus and location and remove the phase tag.

**Comment by tbeck** [comment]
These changes are in place on staging.
commit: 3bc7399
