### ISSUE TITLE
Alternate Graduated designation for portfolio and project page

### ISSUE THREAD

**Issue by abandea** [theirc/airbel#30]
Can we represent graduated projects differently? Can the entire box be grayed out instead, for ex? Or if we have the graduated filter/button, then maybe it's not necessary to tag it differently on the Portfolio page, as it will only show graduated projects (did that make any sense? :)) 

<img width="1089" alt="screen shot 2018-10-02 at 16 46 49" src="https://user-images.githubusercontent.com/42815657/46376270-93e32900-c663-11e8-8a47-fb0f35aeb28b.png">

Relatedly, there's no designation on the project page itself, but I think there should be. Maybe see [issue 29](https://github.com/ocupop/airbel/issues/29#issue-366072449) for example
<img width="1107" alt="screen shot 2018-10-02 at 16 46 11" src="https://user-images.githubusercontent.com/42815657/46376453-08b66300-c664-11e8-8c6a-02983417812d.png">

**Comment by jennyvanderheiden** [comment]
@abandea 
For the designation of graduated project vs. active projects 

- we are proposing a filter where we can drop down graduated and discontinued with Active being the default view.

- we are proposing adding text above the portfolio visualizer, next to the view toggles - letting the user know what they are looking at without having to check the filter status. 

- we are proposing shifting the color of the project box to a darker grey to denote that the graduated and discontinued projects are visually different then active projects in addition to the 'footer' bar.

Mockups to show:
Active: https://gyazo.com/32eb03d0ed9daee5f2e98830294f3419
Graduated: https://gyazo.com/fd0c66a14b88a9e124dc7b2398f1066d
Discontinued: https://gyazo.com/68faf66bf1e7085defd600b72f07f4cc

**Comment by jennyvanderheiden** [comment]
Related:

- Similarly to the text above the visualizer - we are proposing adding in text under "All Projects" to inform the user what lineup they are currently viewing in region or focus.
- https://gyazo.com/0a536c0176eb845f176e154e10b1dc22

**Comment by tbeck** [comment]
Staging is ready for review. We have implemented messaging that more closely reflects the design proposal on #26 

https://icy-ship.cloudvent.net/portfolio
