### ISSUE TITLE
low priority: change text color in Related Articles and Resources

### ISSUE THREAD

**Issue by abandea** [theirc/airbel#31]
The light blue text is a bit hard to read - could we use another designated Airbel color? Or we may have to change the background color

<img width="1165" alt="screen shot 2018-10-02 at 17 02 49" src="https://user-images.githubusercontent.com/42815657/46376828-07396a80-c665-11e8-987f-9c50d043efd8.png">

**Comment by tbeck** [comment]
Sorry about that... We have adjusted to match the comps.
commit: fbbed03
