### ISSUE TITLE
Replace "scribble" vector art with Jenny's updated mock

### ISSUE THREAD

**Issue by benrito** [theirc/airbel#32]
Yuxin, can you generate a new version of this image from Jenny's vector source?

Gotta make sure we get that Star Trek easter egg ;)

![airbel-header-illustration](https://user-images.githubusercontent.com/541325/46433756-b63a7c80-c71f-11e8-83df-02c0b755f00a.png)

[airbel_brand-assets-updated.ai.zip](https://github.com/ocupop/airbel/files/2443475/airbel_brand-assets-updated.ai.zip)

**Comment by jennyvanderheiden** [comment]
On it @benrito!

**Comment by benrito** [comment]
Love it <3
