### ISSUE TITLE
Get Google Analytics code

### ISSUE THREAD

**Issue by benrito** [theirc/airbel#36]

**Comment by benrito** [comment]
@abandea can we ask Giselle's team for the GA code?

**Comment by abandea** [comment]
Hey @benrito - do we want to use IRC's code or our own? What's the benefit of using IRC's code?

**Comment by benrito** [comment]
I think if we can get IRC’s that would be ideal—that way we can see how people are arriving (what % from other IRC properties, etc). Want to reach out to the team? Once we have the code I can add it very easily.

**Comment by abandea** [comment]
That makes sense, I’ll reach out and ask for the code and access to view those metrics as well.

Thanks!
