### ISSUE TITLE
"Graveyard"

### ISSUE THREAD

**Issue by benrito** [theirc/airbel#4]
For future discussion: perhaps a flag for "alive" and a filter on the portfolio visualizer to reveal projects which have been discontinued?

**Comment by tbeck** [comment]
That makes a ton of sense to me. I can add the flag now and we can begin to think through the design considerations for the portfolio visualizer.

I'm assuming that we would still want to create the "non-active" project pages during site build to maintain SEO and historical content value? We can add a visual element on non-active project detail pages to indicate that they have been discontinued.

**Comment by tbeck** [comment]
@benrito - Are projects ever "Completed"?

**Comment by benrito** [comment]
In theory there are two end states:

Discontinued (we do this all the time; learn from failure et etc)

Graduated (successfully spun out; almost always at the scale stage but possibly earlier).

The graduation piece is a bit hypothetical because we haven’t gotten there yet.

Think there’s def value in generating the pages even if they aren’t visible anywhere by default.

Thank you!

**Comment by tbeck** [comment]
What do you think about changing the content/data models to the following?
status:
  - active
  - hidden
  - discontinued
  - graduated

stage:
  1. Identify
  2. Design / Research
  3. Design / Solution Generation
  4. Design / Prototype
  5. Test / Pilot
  6. Test / Rigorous evaluation
  7. Scale

This might account for all of the current scenarios and be flexible enough to accommodate for some process changes in the future?

**Comment by benrito** [comment]
Perfect— to clarify:active will appear by default in the portfolio viewhiddenwill never appear in the portfolio viewdiscontinuedwill appear in the portfolio view but only after the user clicks some kind of filtergraduatedwill appear in the portfolio view but only after the user clicks some kind of filterdiscontinued and graduated are functionally the same but may have UI differences.That would work perfectly.On Sep 5, 2018, at 2:49 PM, Tom Beck <notifications@github.com> wrote:What do you think about changing the content/data models to the following?
status:

active
hidden
discontinued
graduated
stage:



Identify




Design / Research




Design / Solution Generation




Design / Prototype




Test / Pilot




Test / Rigorous evaluation




Scale


This might account for all of the current scenarios and be flexible enough to accommodate for some process changes in the future?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by benrito** [comment]
Yes, I think all pages should generate; the flags affect whether and how they appear in the overall portfolio view. Thoughts?On Sep 5, 2018, at 2:33 PM, Tom Beck <notifications@github.com> wrote:That makes a ton of sense to me. I can add the flag now and we can begin to think through the design considerations for the portfolio visualizer.I'm assuming that we would still want to create the "non-active" project pages during site build to maintain SEO and historical content value? We can add a visual element on non-active project detail pages to indicate that they have been discontinued.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by tbeck** [comment]
Perfect. Thanks Ben!
I have pushed that change here: 29020df

We will use the new configuration as we build out the design this week.

**Comment by benrito** [comment]
Thanks! Should we close this one?

**Comment by tbeck** [comment]
Absolutely... closing now.
