### ISSUE TITLE
Set up domain and SSL cert

### ISSUE THREAD

**Issue by benrito** [theirc/airbel#40]
airbel.rescue.org

airbel.org redirects

**Comment by tbeck** [comment]
Hi @benrito 

Currently Cloudcannon offers a free SSL cert and management (via Let's Encrypt) for domains hosted with them, but not sure if this is how you would prefer to handle hosting etc. ?
https://docs.cloudcannon.com/ssl/letsencrypt/

Let me know if we can help with any of these details.
