### ISSUE TITLE
Add an "explore our work" button above the fold

### ISSUE THREAD

**Issue by benrito** [theirc/airbel#45]
Doing some user testing— some folks are just scrolling through the brochure page and not clicking through to the Portfolio. When I reach over and click for them to the Portfolio page they say "wo!"

Conclusion—we should add a hook, prominently, for people who want to jump right into the portfolio itself.

Recommendation:

"Explore our work" —> Sends visitor directly to Portfolio page

![image](https://user-images.githubusercontent.com/541325/46559446-60500b00-c8be-11e8-86af-780a0f028974.png)

Thoughts?

**Comment by benrito** [comment]
@jennyvanderheiden let me know what you think? We can implement based on your style guide.

**Comment by jennyvanderheiden** [comment]
Hey Ben! I think that is a great idea - just a dark button style.

**Comment by benrito** [comment]
Done! 9ea90922cc6615ad17bd5705b75a96969f4d2a6a
