### ISSUE TITLE
Configure cognito forms for IRC account?

### ISSUE THREAD

**Issue by benrito** [theirc/airbel#47]

**Comment by tbeck** [comment]
@benrito - once you have setup an organization at Cognito forms, can add our Ocupop user (dev@ocupop.com)?

@jonathanwburr - should be able to then transfer the current form to your organization following these details: https://www.cognitoforms.com/support/194/building-forms/copying-forms

**Comment by benrito** [comment]
Alex, can you make us an account?

**Comment by abandea** [comment]
Done (airbel@rescue.org). @tbeck @jonathanwburr just added dev@ocupop.com

**Comment by tbeck** [comment]
Thanks Alex!
We have copied the contact form to the new organization and set notifications to be sent to airbel@rescue.org. 

The new form is up on the staging site here:
https://icy-ship.cloudvent.net/get-in-touch

Let me know if there are any other details that we can help with?

Thanks!
