### ISSUE TITLE
Data model — tagline

### ISSUE THREAD

**Issue by benrito** [theirc/airbel#5]
Hi @tbeck we are starting to stage all the project page content. Noticing that we might want to add a "tagline" field for these:

<img width="655" alt="screen shot 2018-09-20 at 12 00 23 pm" src="https://user-images.githubusercontent.com/541325/45831202-c6d50680-bccc-11e8-8213-b6a298082c89.png">

**Comment by tbeck** [comment]
Hi @benrito - Thanks for catching that!
I've added the tagline field to the defaults and all current instances: dd634cd 

Closing this issue now.
