### ISSUE TITLE
Exclude Discontinued from All Projects

### ISSUE THREAD

**Issue by abandea** [theirc/airbel#50]
Unsure if this is already a feature as this filter is currently blank, but discontinued projects should not be included in the All Projects page, just the interactive portfolio. 

We then need to make sure #49 is resolved as well so that users can access the project page.

@tbeck let me know if I should quickly add a "discontinued" project so you can test this out.

**Comment by tbeck** [comment]
Hi @abandea - The All Projects section only shows projects with a status of active or graduated. Both hidden and discontinued projects are not included.

Here is the specific code:
https://github.com/ocupop/airbel/blob/5767062f285e1b6e5a3dbc3267cd3bfd80405588/src/portfolio.html#L39

**Comment by abandea** [comment]
Thanks for clarifying @tbeck !
