### ISSUE TITLE
Project pages: White space between portfolio visual and body text

### ISSUE THREAD

**Issue by abandea** [theirc/airbel#51]
Noticing there's a gap affecting multiple - if not all - project pages. 

<img width="1440" alt="screen shot 2018-10-24 at 18 30 06" src="https://user-images.githubusercontent.com/42815657/47465410-db6c5900-d7ba-11e8-8398-af79d0353bb3.png">

**Comment by tbeck** [comment]
@abandea - We just pushed a commit to adjust the white space surrounding the portfolio visualizer. Here is a link for review: https://icy-ship.cloudvent.net/projects/caseworker-communications


Thanks!
