### ISSUE TITLE
Project pages: If modules are blank, remove the module

### ISSUE THREAD

**Issue by abandea** [theirc/airbel#52]
One last thing before we launch, we'll be inputting "discontinued" projects soon, many of which don't have a timeline because they were relatively nascent before killing them off. We'll also be adding content around the Mahali Lab, which likely won't have a timeline because it's a special project consisting of many smaller projects.

Any chance we can omit the module entirely if there are no milestones listed? Similarly to the resources/articles modules.

Thanks!

**Comment by abandea** [comment]
Adding in the header/featured image module as well

**Comment by tbeck** [comment]
Hi @abandea!

It looks like logic exists for both the timeline (milestones) section and the resources. I added logic for projects that do not have hero images. 

Here are direct links for review.

Project w/out milestones:
https://icy-ship.cloudvent.net/projects/caseworker-communications

Project w/out hero image:
https://icy-ship.cloudvent.net/projects/ask-laila

**Comment by abandea** [comment]
Whoo - looking good!
