### ISSUE TITLE
Transfer Ocupop cloudcannon to Airbel

### ISSUE THREAD

**Issue by abandea** [theirc/airbel#54]
Account is: Airbel Center, airbel@rescue.org

**Comment by tbeck** [comment]
Hi @abandea - Can you create a Github account for the email: airbel@rescue.org

Once this is in place you should be able to sync with the repository from your Cloudcannon account.
We can also transfer ownership of the repository to this account if that makes sense from your perspective?

Thanks!

**Comment by abandea** [comment]
Hi @tbeck, sounds good. Making sure we don't already have an account, as I see the username is already taken @benrito? If not, I'll create an account and follow up. 

As for the repository, I'm unsure if that needs to be transferred to us or to the IRC specifically.

**Comment by abandea** [comment]
Hey @tbeck, you may have seen that IRC is now the owner of the repo, and airbel-irc is now linked to a cloudcannon account (airbel@rescue.org). Can you kindly transfer the site over?

**Comment by tbeck** [comment]
Hi @abandea - Absolutely. That transfer invitation has been sent.

**Comment by abandea** [comment]
@tbeck received! Super thanks!
