### ISSUE TITLE
Innovation Fund and Project Criterion links do not work 

### ISSUE THREAD

**Issue by abandea** [theirc/airbel#55]
IRC Innovation Fund and Project Criterion link are blank in portfolio page description. Which resources did you want to share? 

[](https://icy-ship.cloudvent.net/portfolio)

**Comment by benrito** [comment]
I removed Fund; Chelsea is going to pull together our criteria for a Medium post we can link. Author should be Ravi.

**Comment by abandea** [comment]
@benrito sounds good, but I think it should be Airbel instead of Ravi, no?
