### ISSUE TITLE
Timeline: Only displays small redirect icon for links

### ISSUE THREAD

**Issue by airbel-irc** [theirc/airbel#57]
Hiya, small thing but something that Chelsea noticed. Whenever you add a new link to timelines, it no longer says "Resource" and only displays the small redirect icon. I don't think people will click on it without the text. Is this a quick fix?

<img width="759" alt="screen shot 2018-11-15 at 12 15 08" src="https://user-images.githubusercontent.com/45015795/48584652-49a6c600-e8f8-11e8-99cc-420c22d007f0.png">

versus 

<img width="921" alt="screen shot 2018-11-15 at 12 15 35" src="https://user-images.githubusercontent.com/45015795/48584659-4e6b7a00-e8f8-11e8-86d0-c5f814763900.png">

**Comment by chelsearescueorg** [comment]
Low priority but still an issue! Flagging for future revisions
