### ISSUE TITLE
Main page — content

### ISSUE THREAD

**Issue by benrito** [theirc/airbel#6]
Hey @tbeck, if you can point us to an html file we can start loading up copy for the main page.

Let us know!

**Comment by tbeck** [comment]
#8 - We can also add the visual editor to the home page. I have to check in with the rest of our team, but I'm hoping that we will be merging the design branch shortly (before 9/24). 

@benrito - Do you think it would make sense to schedule 30 minutes to run through the Cloudcannon CMS with your team and make sure that it is going to work? 
I can answer any questions and at the same time get feedback to better understand how we can optimize the tools for everyone's needs.

**Comment by benrito** [comment]
Now that I've seen the WYSIWIG piece for {{content}}, I am more than sure that Cloudcannon will work. Jaw is still open :)

Happy to connect if useful but don't want to take up more of your time than necessary—we will be able to figure it out once the design branch merges.

Thanks!

**Comment by tbeck** [comment]
Saweet! :)
That is great to hear. We can circle back after the design branch is merged.
