### ISSUE TITLE
Advisory network

### ISSUE THREAD

**Issue by abandea** [theirc/airbel#62]
hi @benrito Logan would like to add the advisory network to the site soon. 

I don't remember: Is it currently set up to live on the "Team" page? Or will it have its own page? If it's the former, than I think we should change "Team" to "Who We Are." It seems a bit awkward to have the network as a "team" but I don't think we need to build another page for just the network.

**Comment by airbel-irc** [comment]
@benrito bumping :) 

Also separate but related:  is there a way to preview the page before "publishing" it

**Comment by benrito** [comment]
Not sure about whether you can do with CloudCannon; but I can show you how to install the whole site locally so you can make changes and then push them live.

**Comment by abandea** [comment]
Ok, I would just like to preview how it looks on the front end before pushing it live, so I would definitely appreciate your guidance here!


On Feb 8, 2019, at 11:43 AM, Ben Moskowitz <notifications@github.com<mailto:notifications@github.com>> wrote:

Not sure about whether you can do with CloudCannon; but I can show you how to install the whole site locally so you can make changes and then push them live.
