### ISSUE TITLE
Team page — content

### ISSUE THREAD

**Issue by benrito** [theirc/airbel#7]
Hi @tbeck — @abandea and I are ready to begin staging the team headshots and titles. If you point us to an html page or give us a pattern we can do that manually.

Thanks!

**Comment by tbeck** [comment]
If you can make updates to the data files we have setup here that would be great. Let me know if we need to adjust any details. I just pushed a change to include a profile image field. 
https://github.com/ocupop/airbel/tree/master/src/_data

Currently we are separating advisors and team into separate files.

Advisors: https://github.com/ocupop/airbel/blob/master/src/_data/advisors.yml
Team: https://github.com/ocupop/airbel/blob/master/src/_data/team.yml

Thanks!
