### ISSUE TITLE
Coach Erevu typo

### ISSUE THREAD

**Issue by abandea** [theirc/airbel#73]
Hi @tbeck,

We just noticed that Coach Erevu was misspelled. We've made the change on the content, but the URL/portfolio name is still misspelled. Would you be able to help? Or show me how to change it? https://airbel.rescue.org/projects/coach-everu/ 

Thanks,
Alex

**Comment by tbeck** [comment]
Hi @abandea,
I just pushed an update to fix this issue. Project content is now available at: https://airbel.rescue.org/projects/coach-erevu/

As part of the fix I added a redirect to avoid any 404 errors. 
https://airbel.rescue.org/projects/coach-everu/

Cheers!
T
