### ISSUE TITLE
Data model — Logline

### ISSUE THREAD

**Issue by benrito** [theirc/airbel#8]
Hey @tbeck, in the mocks realizing that we also need a field for "logline"

i.e., shorter project description that shows up in list view: 

<img width="878" alt="screen shot 2018-09-20 at 12 17 20 pm" src="https://user-images.githubusercontent.com/541325/45832152-2c29f700-bccf-11e8-9980-9f31b62712c8.png">

**Comment by tbeck** [comment]
Hi @benrito - We currently have a "description" field that is meant to serve this purpose, but should we change it to "logline"?

Also... this is assuming that the bulk of the project content would be custom markup in a project instance's "{{ content }}".

Let me know if you think we should make changes to this approach though.

**Comment by benrito** [comment]
Ah, roger! Let's talk it out.

I was assuming that the description field was where we were going to put our marked up content. In that case we'd also need a "logline," for the more condensed copy that appears in the portfolio list view, potentially modals, et etc.

But now I understand that this is what the description field is for.

For the project content, would we be adding a content field so we can update through cloudcannon? Or do you suggest we do manually?

Thanks!

**Comment by tbeck** [comment]
Cloudcannon actually offers a larger portion of their admin to the WYSIWYG editor for the instance "{{ content }}". 
In this screenshot the primary column is reserved for content while the right column is for fields. 
https://gyazo.com/33d09b8a22c62cd36a7800341b61a486

Once we merge the design branch we can also utilize their visual editor for making inline changes... Here is a screenshot from another site for reference: 
https://gyazo.com/f863738c274a3526215e37f81f453ca6

The visual editor makes it much easier to maintain content on pages with more "complex" layouts/designs.

Let me know what you think would work best for your team? I'm assuming that if you are happy with the Cloudcannon solution, we can make adjustments to the configuration/markup to give both technical and non-technical staff the ability to make changes and content updates easily.

**Comment by benrito** [comment]
That works *perfectly*. Didn't realize there's a WYSWIG editor.

Cloudcannon is amazing...
